name: build

on:
  push:
    branches:
      - test-oracular
jobs:
  build-ubuntu:
    strategy:
      matrix:
        tag: [noble, oracular]
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v4
    - name: Docker Build
      run: |
        docker build -f deployment/Dockerfile.debian -t builddeb --build-arg TAG=${{ matrix.tag }} --build-arg IMG=ubuntu deployment
        docker run -v $(pwd)/deployment/dist:/dist -v $(pwd):/jellyfin -e TAG=${{ matrix.tag }} builddeb
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-${{ matrix.tag }}
        path: ${{ github.workspace }}/deployment/dist/*
